In [72]:
import pandas as pd
import numpy as np

In [73]:
#4c
np.set_printoptions(4, suppress=True)
for i in range (0,3):
    print('*** matrix ***')
    m = np.random.randint(-10, 11, (3,3))
    print(m)
    try:
        m_inv = np.linalg.inv(m)
        print('*** Inverse ***')
        print(m_inv)
        print('*** m * m_inverse ***')
        print(np.matmul(m, m_inv))
    except LinAlgError as e:
        print("matrix is not invertible")

*** matrix ***
[[ -5 -10   9]
 [  9  10  -4]
 [  2   0  -4]]
*** Inverse ***
[[ 0.1538  0.1538  0.1923]
 [-0.1077 -0.0077 -0.2346]
 [ 0.0769  0.0769 -0.1538]]
*** m * m_inverse ***
[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
*** matrix ***
[[ 5  4  4]
 [ 0 -7 -2]
 [10 -3  5]]
*** Inverse ***
[[  8.2   6.4  -4. ]
 [  4.    3.   -2. ]
 [-14.  -11.    7. ]]
*** m * m_inverse ***
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
*** matrix ***
[[ -7   4  -4]
 [-10  10   4]
 [ -1   4   0]]
*** Inverse ***
[[-0.0741 -0.0741  0.2593]
 [-0.0185 -0.0185  0.3148]
 [-0.1389  0.1111 -0.1389]]
*** m * m_inverse ***
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


In [74]:
df = pd.read_csv("kc_house_data.csv")
df = df.drop(columns = ["id", "date", "zipcode"])

In [75]:
#5a
# calculate average
print("Feature Average:")
mean = df.mean()
print(mean, "\n")

# calculate max
print("Feature Max")
print(df.max(), "\n")

# calculate min
print("Feature Min")
print(df.max(), "\n")

# calculate variance
print("Feature Variance")
variance = df.var()
print(variance, "\n")

Feature Average:
price            540088.141767
bedrooms              3.370842
bathrooms             2.114757
sqft_living        2079.899736
sqft_lot          15106.967566
floors                1.494309
waterfront            0.007542
view                  0.234303
condition             3.409430
grade                 7.656873
sqft_above         1788.390691
sqft_basement       291.509045
yr_built           1971.005136
yr_renovated         84.402258
lat                  47.560053
long               -122.213896
sqft_living15      1986.552492
sqft_lot15        12768.455652
dtype: float64 

Feature Max
price            7.700000e+06
bedrooms         3.300000e+01
bathrooms        8.000000e+00
sqft_living      1.354000e+04
sqft_lot         1.651359e+06
floors           3.500000e+00
waterfront       1.000000e+00
view             4.000000e+00
condition        5.000000e+00
grade            1.300000e+01
sqft_above       9.410000e+03
sqft_basement    4.820000e+03
yr_built         2.015000e+03
yr_ren

In [76]:
print("Highest Average:")
print (pd.DataFrame({'feature':mean.index, 'value':mean.values}).max(), "\n")
print ("Lowest Average:")
print (pd.DataFrame({'feature':mean.index, 'value':mean.values}).min(), "\n")

print("Highest Variance:")
print (pd.DataFrame({'feature':variance.index, 'value':variance.values}).max(), "\n")
print ("Lowest Variance:")
print (pd.DataFrame({'feature':variance.index, 'value':variance.values}).min(), "\n")


Highest Average:
feature     yr_renovated
value      540088.141767
dtype: object 

Lowest Average:
feature     bathrooms
value     -122.213896
dtype: object 

Highest Variance:
feature           yr_renovated
value      134782378397.246811
dtype: object 

Lowest Variance:
feature    bathrooms
value       0.007485
dtype: object 



In [94]:
#5b
max_corr = -10000
max_feature_row = ""
max_feature_col = ""
corr = df.corr()
for col in corr:
    drop_self = corr[col].drop(index = col)
    temp = pd.DataFrame({'feature':drop_self.index, 'correlation':drop_self.values})
    max_temp_corr = temp.max()
    if (max_temp_corr['correlation'] > max_corr):
        max_corr = max_temp_corr['correlation']
        max_feature_row = max_temp_corr['feature']
        max_feature_col = col
print ("features with highest correlation coefficient: ", max_feature_row, " ", max_feature_col)
print (max_corr)

price
bedrooms
bathrooms
sqft_living
sqft_lot
floors
waterfront
view
condition
grade
sqft_above
sqft_basement
yr_built
yr_renovated
lat
long
sqft_living15
sqft_lot15
features with highest correlation coefficient:  yr_renovated   sqft_living
0.8765965986813202


In [78]:
corr

price  bedrooms  bathrooms  sqft_living  sqft_lot    floors  \
price          1.000000  0.308350   0.525138     0.702035  0.089661  0.256794   
bedrooms       0.308350  1.000000   0.515884     0.576671  0.031703  0.175429   
bathrooms      0.525138  0.515884   1.000000     0.754665  0.087740  0.500653   
sqft_living    0.702035  0.576671   0.754665     1.000000  0.172826  0.353949   
sqft_lot       0.089661  0.031703   0.087740     0.172826  1.000000 -0.005201   
floors         0.256794  0.175429   0.500653     0.353949 -0.005201  1.000000   
waterfront     0.266369 -0.006582   0.063744     0.103818  0.021604  0.023698   
view           0.397293  0.079532   0.187737     0.284611  0.074710  0.029444   
condition      0.036362  0.028472  -0.124982    -0.058753 -0.008958 -0.263768   
grade          0.667434  0.356967   0.664983     0.762704  0.113621  0.458183   
sqft_above     0.605567  0.477600   0.685342     0.876597  0.183512  0.523885   
sqft_basement  0.323816  0.303093   0.283770     0.435043  0.015286 -0.245705   
yr_built       0.054012  0.154178   0.506019     0.318049  0.053080  0.489319   
yr_renovated   0.126434  0.018841   0.050739     0.055363  0.007644  0.006338   
lat            0.307003 -0.008931   0.024573     0.052529 -0.085683  0.049614   
long           0.021626  0.129473   0.223042     0.240223  0.229521  0.125419   
sqft_living15  0.585379  0.391638   0.568634     0.756420  0.144608  0.279885   
sqft_lot15     0.082447  0.029244   0.087175     0.183286  0.718557 -0.011269   

               waterfront      view  condition     grade  sqft_above  \
price            0.266369  0.397293   0.036362  0.667434    0.605567   
bedrooms        -0.006582  0.079532   0.028472  0.356967    0.477600   
bathrooms        0.063744  0.187737  -0.124982  0.664983    0.685342   
sqft_living      0.103818  0.284611  -0.058753  0.762704    0.876597   
sqft_lot         0.021604  0.074710  -0.008958  0.113621    0.183512   
floors           0.023698  0.029444  -0.263768  0.458183    0.523885   
waterfront       1.000000  0.401857   0.016653  0.082775    0.072075   
view             0.401857  1.000000   0.045990  0.251321    0.167649   
condition        0.016653  0.045990   1.000000 -0.144674   -0.158214   
grade            0.082775  0.251321  -0.144674  1.000000    0.755923   
sqft_above       0.072075  0.167649  -0.158214  0.755923    1.000000   
sqft_basement    0.080588  0.276947   0.174105  0.168392   -0.051943   
yr_built        -0.026161 -0.053440  -0.361417  0.446963    0.423898   
yr_renovated     0.092885  0.103917  -0.060618  0.014414    0.023285   
lat             -0.014274  0.006157  -0.014941  0.114084   -0.000816   
long            -0.041910 -0.078400  -0.106500  0.198372    0.343803   
sqft_living15    0.086463  0.280439  -0.092824  0.713202    0.731870   
sqft_lot15       0.030703  0.072575  -0.003406  0.119248    0.194050   

               sqft_basement  yr_built  yr_renovated       lat      long  \
price               0.323816  0.054012      0.126434  0.307003  0.021626   
bedrooms            0.303093  0.154178      0.018841 -0.008931  0.129473   
bathrooms           0.283770  0.506019      0.050739  0.024573  0.223042   
sqft_living         0.435043  0.318049      0.055363  0.052529  0.240223   
sqft_lot            0.015286  0.053080      0.007644 -0.085683  0.229521   
floors             -0.245705  0.489319      0.006338  0.049614  0.125419   
waterfront          0.080588 -0.026161      0.092885 -0.014274 -0.041910   
view                0.276947 -0.053440      0.103917  0.006157 -0.078400   
condition           0.174105 -0.361417     -0.060618 -0.014941 -0.106500   
grade               0.168392  0.446963      0.014414  0.114084  0.198372   
sqft_above         -0.051943  0.423898      0.023285 -0.000816  0.343803   
sqft_basement       1.000000 -0.133124      0.071323  0.110538 -0.144765   
yr_built           -0.133124  1.000000     -0.224874 -0.148122  0.409356   
yr_renovated        0.071323 -0.224874      1